### ISSUE TITLE
Generate widget plugin

### ISSUE THREAD

**Issue by zzotta** [andreanegri/pythonutils#6]
* includere QDesignerCustomWidgetCollectionInterface invece di QDesigner nell'header della collection
* correggere case nomi classi generate (Ui_...., inclusione header del plugin collection)
* derivazione privata dell'UI
* scelta modalita' di generazione relazione classe/UI

**Comment by andreanegri** [comment]
Non ho dovuto però includere QDesignerCustomWidgetCollectionInterface, @zzotta puoi verificare se funziona?
